//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFClassLibrary.IDOWebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://frontstep.com/IDOWebService", ConfigurationName="IDOWebServiceReference.IDOWebServiceSoap")]
    public interface IDOWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/GetConfigurationNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetConfigurationNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/CreateSessionToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateSessionToken(string strUserId, string strPswd, string strConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/LoadDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoadDataSet(string strSessionToken, string strIDOName, string strPropertyList, string strFilter, string strOrderBy, string strPostQueryMethod, int iRecordCap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/SaveDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SaveDataSet(string strSessionToken, System.Data.DataSet updateDataSet, bool refreshAfterSave, string strCustomInsert, string strCustomUpdate, string strCustomDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/CallMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object CallMethod(string strSessionToken, string strIDOName, string strMethodName, ref string strMethodParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/LoadJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoadJson(string strSessionToken, string strIDOName, string strPropertyList, string strFilter, string strOrderBy, string strPostQueryMethod, int iRecordCap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://frontstep.com/IDOWebService/SaveJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveJson(string strSessionToken, string updateJsonObject, string strCustomInsert, string strCustomUpdate, string strCustomDelete);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDOWebServiceSoapChannel : WTFClassLibrary.IDOWebServiceReference.IDOWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOWebServiceSoapClient : System.ServiceModel.ClientBase<WTFClassLibrary.IDOWebServiceReference.IDOWebServiceSoap>, WTFClassLibrary.IDOWebServiceReference.IDOWebServiceSoap {
        
        public DOWebServiceSoapClient() {
        }
        
        public DOWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetConfigurationNames() {
            return base.Channel.GetConfigurationNames();
        }
        
        public string CreateSessionToken(string strUserId, string strPswd, string strConfig) {
            return base.Channel.CreateSessionToken(strUserId, strPswd, strConfig);
        }
        
        public System.Data.DataSet LoadDataSet(string strSessionToken, string strIDOName, string strPropertyList, string strFilter, string strOrderBy, string strPostQueryMethod, int iRecordCap) {
            return base.Channel.LoadDataSet(strSessionToken, strIDOName, strPropertyList, strFilter, strOrderBy, strPostQueryMethod, iRecordCap);
        }
        
        public System.Data.DataSet SaveDataSet(string strSessionToken, System.Data.DataSet updateDataSet, bool refreshAfterSave, string strCustomInsert, string strCustomUpdate, string strCustomDelete) {
            return base.Channel.SaveDataSet(strSessionToken, updateDataSet, refreshAfterSave, strCustomInsert, strCustomUpdate, strCustomDelete);
        }
        
        public object CallMethod(string strSessionToken, string strIDOName, string strMethodName, ref string strMethodParameters) {
            return base.Channel.CallMethod(strSessionToken, strIDOName, strMethodName, ref strMethodParameters);
        }
        
        public string LoadJson(string strSessionToken, string strIDOName, string strPropertyList, string strFilter, string strOrderBy, string strPostQueryMethod, int iRecordCap) {
            return base.Channel.LoadJson(strSessionToken, strIDOName, strPropertyList, strFilter, strOrderBy, strPostQueryMethod, iRecordCap);
        }
        
        public string SaveJson(string strSessionToken, string updateJsonObject, string strCustomInsert, string strCustomUpdate, string strCustomDelete) {
            return base.Channel.SaveJson(strSessionToken, updateJsonObject, strCustomInsert, strCustomUpdate, strCustomDelete);
        }
    }
}
