//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingSlip
    {
        public long ID { get; set; }
        public string PackingSlipNo { get; set; }
        public string OrderLinePrefix { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string OrderNotes { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerOrderSuffix { get; set; }
        public Nullable<System.DateTime> ActualShipDate { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NoOfCartons { get; set; }
        public Nullable<decimal> NoOfPallets { get; set; }
        public string JobNumber { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> CustomerOrderLine { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> QtyOrdered { get; set; }
        public Nullable<decimal> QtyShipped { get; set; }
        public Nullable<decimal> QtyBackOrdered { get; set; }
        public string Revision { get; set; }
        public Nullable<int> CustomerOrderRelease { get; set; }
        public string CustomerPO { get; set; }
    }
}
