//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFClassLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryDefs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryDefs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTFClassLibrary.QueryDefs", typeof(QueryDefs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ItemUnitWeightHistory 
        ///WHERE item = &apos;~p0&apos; AND RecordedTimestamp = (SELECT MIN(RecordedTimestamp) FROM ItemUnitWeightHistory WHERE item = &apos;~p0&apos;).
        /// </summary>
        internal static string DeleteOldestItemUnitWeightHistory {
            get {
                return ResourceManager.GetString("DeleteOldestItemUnitWeightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(AVG(UnitWeight), 0), COUNT(UnitWeight) 
        ///FROM ItemUnitWeightHistory 
        ///WHERE Item = &apos;~p0&apos;.
        /// </summary>
        internal static string GetItemAvgUnitWeightAndCount {
            get {
                return ResourceManager.GetString("GetItemAvgUnitWeightAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NextSequence, GUID From TableSequence 
        ///	WHERE (TableName = &apos;~p0&apos;).
        /// </summary>
        internal static string GetNextSequenceNumber {
            get {
                return ResourceManager.GetString("GetNextSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO jobtran(job, suffix, trans_type, trans_date, qty_complete, oper_num, qty_moved, whse, loc, trans_class, wc, user_code, complete_op, close_job, next_oper, qty_scrapped)
        ///	Values(&apos;~p0&apos;, ~p1, &apos;~p2&apos;, &apos;~p3&apos;, ~p4, ~p5, ~p6, &apos;~p7&apos;, &apos;~p8&apos;, &apos;~p9&apos;, &apos;~p10&apos;, &apos;~p11&apos;, ~p12, ~p13, ~p14, 0).
        /// </summary>
        internal static string InsertIntoJobTran {
            get {
                return ResourceManager.GetString("InsertIntoJobTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ReceivedItemAccumulator 
        ///	(item, job, JobOrderNumber, TotalQuantity, suffix) VALUES (&apos;~p0&apos;, &apos;~p1&apos;, &apos;~p2&apos;, ~p3, ~p4).
        /// </summary>
        internal static string InsertIntoRecievedItemAccumulator {
            get {
                return ResourceManager.GetString("InsertIntoRecievedItemAccumulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ReceivedItemHistory(job, item, quantity, operator, GrossWgt, LabelSequence, co, PalletCt, suffix)
        ///	VALUES (&apos;~p0&apos;, &apos;~p1&apos;, ~p2, &apos;~p3&apos;, ~p4, ~p5, &apos;~p6&apos;, ~p7, ~p8).
        /// </summary>
        internal static string InsertIntoRecievedItemHistory {
            get {
                return ResourceManager.GetString("InsertIntoRecievedItemHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ItemUnitWeightHistory(item, UnitWeight, Quantity) VALUES (&apos;~p0&apos;, &apos;~p1&apos;, &apos;~p2&apos;).
        /// </summary>
        internal static string InsertNewItemUnitWeightHistory {
            get {
                return ResourceManager.GetString("InsertNewItemUnitWeightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rpt_PurchaseRequirementsSp {
            get {
                return ResourceManager.GetString("Rpt_PurchaseRequirementsSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LabelSequence, item, job, co, Quantity, ReceivedTimestamp, ShippedTimestamp, operator, GrossWgt, PalletCt, ReceivedItemID, suffix 
        ///	FROM ReceivedItemHistory 
        ///	WHERE Item = &apos;~p0&apos; ~p1
        ///	ORDER BY LabelSequence ASC.
        /// </summary>
        internal static string SelectAllItemHistory {
            get {
                return ResourceManager.GetString("SelectAllItemHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cust_num, Name, Addr##1, Addr##2, Addr##3, Addr##4, City, State, ZIP, Country
        ///	FROM CustAddr
        ///	WHERE cust_num = ~p0
        ///	ORDER BY cust_seq.
        /// </summary>
        internal static string SelectCustomerAddresses {
            get {
                return ResourceManager.GetString("SelectCustomerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [cust-num], CustomerLabelID, Description, LabelFile, AddrLineCt, SupplierNumber, Sequence
        ///	FROM CustomerLabel
        ///	WHERE [cust-num] = 0 OR [cust-num] = ~p0
        ///	ORDER BY [cust-num] desc, Sequence ASC, description ASC.
        /// </summary>
        internal static string SelectCustomerLabels {
            get {
                return ResourceManager.GetString("SelectCustomerLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUM(TotalQuantity) FROM ReceivedItemAccumulator
        ///	WHERE item = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectItemAccumulatorAvailableInventory {
            get {
                return ResourceManager.GetString("SelectItemAccumulatorAvailableInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT job.job, co.co_num, coitem.co_release, job.qty_released, job.qty_complete, item.description, 
        ///item.u_m, co.cust_po, job.ord_release, job.ord_num, itemwhse.qty_on_hand, co_bln.cust_item, custaddr.name, 
        ///co.cust_num, shipcode.description AS ShipCodeDescription, 
        ///terms.description AS Terms, item.drawing_nbr, item.charfld1, item.charfld1, coitem.due_date
        ///FROM co_bln
        ///INNER JOIN item ON co_bln.item = item.item
        ///INNER JOIN coitem ON co_bln.item = coitem.item AND coitem.co_num = co_bln.co_num
        ///INNER JOI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectItemBlanketJobs {
            get {
                return ResourceManager.GetString("SelectItemBlanketJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT job.job, job.ord_num, co.co_num, coitem.co_line, coitem.co_release, 
        ///job.qty_released, coitem.qty_ordered, coitem.qty_shipped, 
        ///coitem.qty_ready, co.cust_po, coitem.ship_date, 
        ///coitem.due_date, coitem.cust_item, custaddr.name, 
        ///shipcode.description AS ShipCodeDescription, terms.description AS Terms, item.drawing_nbr, item.charfld1, 
        ///co.slsman, item.description, item.revision, co.cust_num, itemwhse.qty_on_hand
        ///FROM co INNER JOIN coitem ON co.co_num = coitem.co_num
        ///INNER JOIN item ON coitem.item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectItemJobs {
            get {
                return ResourceManager.GetString("SelectItemJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT job, TotalQuantity, JobOrderNumber, LastUpdate, ReceivedItemAccumulatorID, suffix
        ///FROM ReceivedItemAccumulator
        ///WHERE item = &apos;~p0&apos;
        ///AND TotalQuantity ~p1.
        /// </summary>
        internal static string SelectItemJobsFromInventory {
            get {
                return ResourceManager.GetString("SelectItemJobsFromInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT whse, item, rank, loc, loc_type
        ///	FROM itemloc
        ///	WHERE whse = &apos;~p0&apos; AND item = &apos;~p1&apos; AND loc_type = &apos;S&apos;
        ///	ORDER BY rank ASC.
        /// </summary>
        internal static string SelectItemStockRoomLocations {
            get {
                return ResourceManager.GetString("SelectItemStockRoomLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT oper_num, wc, qty_complete, qty_scrapped, qty_moved, complete AS Status
        ///	FROM jobroute
        ///	WHERE suffix = 0 AND job = &apos;~p0&apos;
        ///	ORDER BY oper_num ~p1.
        /// </summary>
        internal static string SelectJobOperations {
            get {
                return ResourceManager.GetString("SelectJobOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(ReceivedTimestamp) FROM ReceivedItemHistory
        ///	WHERE item = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectLastRecievedItemHistoryDate {
            get {
                return ResourceManager.GetString("SelectLastRecievedItemHistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(ShippedTimestamp) FROM ReceivedItemHistory 
        ///	WHERE item = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectLastShippedItemHistoryDate {
            get {
                return ResourceManager.GetString("SelectLastShippedItemHistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT job.job, job.suffix, job.qty_released, job.qty_complete, item.description, item.u_m, job.ord_release, job.ord_num, itemwhse.qty_on_hand, item.drawing_nbr, item.charfld1
        ///FROM item INNER JOIN job ON item.item = job.item 
        ///INNER JOIN itemwhse ON item.item = itemwhse.item
        ///WHERE job.type=&apos;J&apos; AND item.item=&apos;~p0&apos; AND (job.stat = &apos;R&apos; OR job.stat = &apos;F&apos;)
        ///AND itemwhse.whse =&apos;MAIN&apos; ORDER BY job.job.
        /// </summary>
        internal static string SelectMFGItemJobs {
            get {
                return ResourceManager.GetString("SelectMFGItemJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT job.job, job.suffix, job.qty_released, job.qty_complete, item.description, item.u_m, job.ord_release, job.ord_num, itemwhse.qty_on_hand, item.drawing_nbr, item.charfld1
        ///FROM item INNER JOIN job ON item.item = job.item 
        ///INNER JOIN itemwhse ON item.item = itemwhse.item
        ///WHERE job.type=&apos;J&apos; AND item.item=&apos;~p0&apos; AND job.job IN (~p1)
        ///AND itemwhse.whse =&apos;MAIN&apos; ORDER BY job.job.
        /// </summary>
        internal static string SelectMFGItemJobsByJobList {
            get {
                return ResourceManager.GetString("SelectMFGItemJobsByJobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// co.co_num
        ///,co.cust_num
        ///,coitem.co_line
        ///,coitem.co_release
        ///,coitem.qty_ordered
        ///,coitem.qty_shipped
        ///,co.cust_po
        ///,co.slsman
        ///,item.item
        ///,item.drawing_nbr
        ///,item.charfld1
        ///,item.description AS ItemDescription
        ///,item.revision
        ///,coitem.qty_ready
        ///,coitem.ship_date
        ///,coitem.due_date
        ///,coitem.promise_date
        ///,coitem.cust_item
        ///,custaddr.name
        ///,shipcode.description AS ShipCodeDescription
        ///,terms.description AS TermsDescription
        ///,co.stat AS OrderStatus
        ///,coitem.stat
        ///FROM co INNER JOIN coitem ON co.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectMFGItemOrderLines {
            get {
                return ResourceManager.GetString("SelectMFGItemOrderLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// co.co_num
        ///,co.cust_num
        ///,coitem.co_line
        ///,coitem.co_release
        ///,coitem.qty_ordered
        ///,coitem.qty_shipped
        ///,co.cust_po
        ///,co.slsman
        ///,item.item
        ///,item.drawing_nbr
        ///,item.charfld1
        ///,item.description AS ItemDescription
        ///,item.revision
        ///,coitem.qty_ready
        ///,coitem.ship_date
        ///,coitem.promise_date
        ///,coitem.due_date
        ///,coitem.cust_item
        ///,custaddr.name
        ///,shipcode.description AS ShipCodeDescription
        ///,terms.description AS TermsDescription
        ///,co.stat AS OrderStatus
        ///,coitem.stat
        ///FROM co INNER JOIN coitem ON co.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectMFGItemOrderLinesFilled {
            get {
                return ResourceManager.GetString("SelectMFGItemOrderLinesFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT co.co_num, co.type, coitem.co_line, co.cust_po, coitem.cust_item, co.cust_num, custaddr.name, co.order_date, co.cust_seq, co.decifld1
        ///FROM co 
        ///INNER JOIN coitem ON co.co_num = coitem.co_num 
        ///INNER JOIN customer ON co.cust_num = customer.cust_num AND co.cust_seq = customer.cust_seq
        ///INNER JOIN custaddr ON customer.cust_seq = custaddr.cust_seq AND customer.cust_num = custaddr.cust_num
        ///WHERE coitem.item = &apos;~p0&apos; 
        ///AND co.stat=&apos;O&apos; AND coitem.stat=&apos;O&apos;.
        /// </summary>
        internal static string SelectMFGItemOrders {
            get {
                return ResourceManager.GetString("SelectMFGItemOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT co.co_num, co.type, coitem.co_line, co.cust_po, coitem.cust_item, co.cust_num, custaddr.name, co.order_date, co.cust_seq, co.decifld1
        ///FROM co 
        ///INNER JOIN coitem ON co.co_num = coitem.co_num 
        ///INNER JOIN customer ON co.cust_num = customer.cust_num AND co.cust_seq = customer.cust_seq
        ///INNER JOIN custaddr ON customer.cust_seq = custaddr.cust_seq AND customer.cust_num = custaddr.cust_num
        ///WHERE coitem.item = &apos;~p0&apos; 
        ///AND (co.stat=&apos;O&apos; OR co.stat=&apos;C&apos;)
        ///ORDER BY co.co_num, coitem.co_line.
        /// </summary>
        internal static string SelectMFGItemOrdersFilled {
            get {
                return ResourceManager.GetString("SelectMFGItemOrdersFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Description, Note, IsSpecificNote, TableName, RefRowPointer, IsInternalNote
        ///FROM ReportNotesView
        ///WHERE RefRowPointer = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectNotesByGUID {
            get {
                return ResourceManager.GetString("SelectNotesByGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// co.co_num
        ///,co.contact
        ///,co.cust_num
        ///,coitem.co_line
        ///,coitem.co_release
        ///,coitem.qty_ordered
        ///,coitem.qty_shipped
        ///,co.cust_po
        ///,co.slsman
        ///,item.item
        ///,item.drawing_nbr
        ///,item.charfld1
        ///,item.description AS ItemDescription
        ///,item.revision
        ///,coitem.qty_ready
        ///,coitem.ship_date
        ///,coitem.promise_date
        ///,coitem.due_date
        ///,coitem.cust_item
        ///,custaddr.name
        ///,shipcode.description AS ShipCodeDescription
        ///,terms.description AS TermsDescription
        ///,co.stat AS OrderStatus
        ///,coitem.stat
        ///,item.u_m
        ///,coitem.Ro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectOrderOrderLines {
            get {
                return ResourceManager.GetString("SelectOrderOrderLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ReceivedItemAccumulatorID, JobOrderNumber
        ///	FROM ReceivedItemAccumulator 
        ///	WHERE item = &apos;~p0&apos; AND job = &apos;~p1&apos;AND suffix = ~p2.
        /// </summary>
        internal static string SelectRecievedAccumulatorID {
            get {
                return ResourceManager.GetString("SelectRecievedAccumulatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LabelSequence, item, job, co, Quantity, ReceivedTimestamp, ShippedTimestamp, operator, GrossWgt, PalletCt, ReceivedItemID, suffix
        ///	FROM ReceivedItemHistory 
        ///	WHERE Item = &apos;~p0&apos; ~p1
        ///	AND ShippedTimestamp IS NULL
        ///	ORDER BY LabelSequence ASC.
        /// </summary>
        internal static string SelectRecievedItemHistory {
            get {
                return ResourceManager.GetString("SelectRecievedItemHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Setting
        ///	FROM Settings
        ///	WHERE KeyName = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectSetting {
            get {
                return ResourceManager.GetString("SelectSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LabelSequence, item, job, co, Quantity, ReceivedTimestamp, ShippedTimestamp, operator, GrossWgt, PalletCt, ReceivedItemID, suffix
        ///	FROM ReceivedItemHistory 
        ///	WHERE Item = &apos;~p0&apos; ~p1
        ///	AND ShippedTimestamp IS NOT NULL
        ///	ORDER BY LabelSequence ASC.
        /// </summary>
        internal static string SelectShippedItemHistory {
            get {
                return ResourceManager.GetString("SelectShippedItemHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ShipCarriersID, CarrierDesc 
        ///	FROM ShipCarriers 
        ///	ORDER BY CarrierDesc.
        /// </summary>
        internal static string SelectShippingCarriers {
            get {
                return ResourceManager.GetString("SelectShippingCarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ItemRef, ItemDesc + &apos; &apos; + ItemNo + &apos; &apos; + Class AS Classification 
        ///	FROM ShipClassification 
        ///	ORDER BY ItemRef.
        /// </summary>
        internal static string SelectShippingClassifications {
            get {
                return ResourceManager.GetString("SelectShippingClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT loc, description, loc_type
        ///	FROM location.
        /// </summary>
        internal static string SelectStockRoomLocations {
            get {
                return ResourceManager.GetString("SelectStockRoomLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP ~p0 cust_num, Name, Addr##1, Addr##2, Addr##3, Addr##4, City, State, ZIP, Country
        ///	FROM CustAddr
        ///	WHERE ~p1 Like &apos;%~p2%&apos;
        ///	ORDER BY ~p3.
        /// </summary>
        internal static string SelectTopNCustomerAddresses {
            get {
                return ResourceManager.GetString("SelectTopNCustomerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP ~p0 item.[item], item.[description], item.revision, item.drawing_nbr, item.charfld1, itemwhse.qty_on_hand
        ///	FROM item INNER JOIN itemwhse ON item.item = itemwhse.item
        ///	WHERE ~p1 LIKE &apos;~p2%&apos;
        ///	ORDER BY ~p3.
        /// </summary>
        internal static string SelectTopNItems {
            get {
                return ResourceManager.GetString("SelectTopNItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP ~p0 co.co_num, co.type, co.cust_po, co.cust_num, custaddr.name, co.order_date, co.decifld1, co.RowPointer, co.cust_seq
        ///FROM co 
        ///INNER JOIN customer ON co.cust_num = customer.cust_num AND co.cust_seq = customer.cust_seq
        ///INNER JOIN custaddr ON customer.cust_seq = custaddr.cust_seq AND customer.cust_num = custaddr.cust_num
        ///WHERE LTRIM(RTRIM(~p1)) LIKE &apos;%~p2%&apos;
        ///AND (co.stat=&apos;O&apos; OR co.stat=&apos;C&apos;)
        ///ORDER BY ~p3.
        /// </summary>
        internal static string SelectTopNOrders {
            get {
                return ResourceManager.GetString("SelectTopNOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP ~p0 vend_num, Name, Addr##1, Addr##2, Addr##3, Addr##4, City, State, ZIP, Country
        ///	FROM VendAddr
        ///	WHERE ~p1 Like &apos;%~p2%&apos;
        ///	ORDER BY ~p3.
        /// </summary>
        internal static string SelectTopNVendorAddresses {
            get {
                return ResourceManager.GetString("SelectTopNVendorAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TableSequence
        ///	SET NextSequence = ~p0, GUID = &apos;~p1&apos; 
        ///	WHERE TableName = &apos;~p2&apos; AND GUID = &apos;~p3&apos;.
        /// </summary>
        internal static string UpdateNextSequenceNumber {
            get {
                return ResourceManager.GetString("UpdateNextSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE co 
        ///SET decifld1 = decifld1 + 1 
        ///WHERE LTRIM(RTRIM(co_num)) = &apos;~p0&apos;.
        /// </summary>
        internal static string UpdatePackingSlipPrintSequence {
            get {
                return ResourceManager.GetString("UpdatePackingSlipPrintSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ReceivedItemAccumulator
        ///	SET TotalQuantity = TotalQuantity ~p0, LastUpdate = &apos;~p1&apos;, JobOrderNumber= &apos;~p2&apos;
        ///	WHERE ReceivedItemAccumulatorID = ~p3.
        /// </summary>
        internal static string UpdateRecievedItemAccumulator {
            get {
                return ResourceManager.GetString("UpdateRecievedItemAccumulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ReceivedItemHistory
        ///	SET ShippedTimestamp = &apos;~p0&apos;
        ///	WHERE ReceivedItemID = ~p1.
        /// </summary>
        internal static string UpdateRecievedItemHistory {
            get {
                return ResourceManager.GetString("UpdateRecievedItemHistory", resourceCulture);
            }
        }
    }
}
