//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrongCount
    {
        public int ID { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> OccurranceDate { get; set; }
    }
}
